/**
 * @file kernel/fs/ramdisk.hpp
 * @brief Ramdisk driver for parsing embedded ustar initrd archives
 *
 * Provides a Ramdisk class that parses a ustar-format initial ramdisk
 * embedded in the kernel binary.  The archive is accessed via linker
 * symbols (_binary_initrd_start / _binary_initrd_end) generated by
 * CMake from an external .tar file.
 *
 * Ramdisk inherits from FileSystem, implementing mount() to parse the
 * ustar archive and lookup() to find files by path.  Each file found
 * during mount is recorded with its name, data pointer, and size, and
 * a corresponding Inode is pre-allocated with Ramdisk-specific InodeOps.
 *
 * Usage:
 *   cinux::fs::Ramdisk rd;
 *   rd.mount();                  // parse the embedded initrd
 *   Inode* ino = rd.lookup("hello.txt");  // find a file
 *
 * Namespace: cinux::fs
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

#include "fs/vfs_filesystem.hpp"

namespace cinux::fs {

// ============================================================
// Ramdisk Limits
// ============================================================

/// Maximum displayable file name length (for safe printing)
static constexpr uint32_t RAMDISK_NAME_MAX = 100;

/// Maximum number of file entries the ramdisk can track
static constexpr uint32_t RAMDISK_MAX_ENTRIES = 64;

// ============================================================
// Ramdisk Entry Info
// ============================================================

/**
 * @brief Describes a single file entry found in the ramdisk
 */
struct RamdiskEntry {
    char        name[RAMDISK_NAME_MAX];  ///< Null-terminated file name
    uint64_t    size;                    ///< File size in bytes (parsed from octal)
    const void* data;                    ///< Pointer to the file data within the archive
    Inode       inode;                   ///< Pre-allocated Inode for this entry
};

/**
 * @brief Context passed to the ramdisk root directory's readdir InodeOp
 *
 * Allows the readdir function to iterate over the entry table without
 * needing direct access to the Ramdisk private members.
 */
struct RamdiskDirContext {
    const RamdiskEntry* entries;  ///< Pointer to the entry table
    uint32_t            count;    ///< Number of entries in the table
};

// ============================================================
// Ramdisk Class
// ============================================================

/**
 * @brief Parses and provides access to a ustar-format initial ramdisk
 *
 * On mount(), iterates through all ustar entries in the embedded
 * archive, validates each header's magic field, and builds an
 * internal entry table.  Each file entry gets a pre-allocated Inode
 * with Ramdisk-specific InodeOps (read from archive data, write
 * returns error, readdir returns entries).
 *
 * The ramdisk is embedded at link time via CMake's add_custom_command
 * which converts a .tar file into a linkable object with symbols
 * _binary_initrd_start and _binary_initrd_end.
 */
class Ramdisk : public FileSystem {
public:
    /**
     * @brief Mount and parse the embedded initrd archive
     *
     * Reads the ustar archive bounded by the linker symbols
     * _binary_initrd_start and _binary_initrd_end.  For each valid
     * entry (magic == "ustar"), builds a RamdiskEntry with the file
     * name, data pointer, size, and a pre-allocated Inode.
     *
     * @return true if at least one entry was parsed, false otherwise
     */
    bool mount() override;

    /**
     * @brief Look up a file by its path within the ramdisk
     *
     * Searches the internal entry table for a file whose name matches
     * the given path.  The path should be relative to the ramdisk root
     * (e.g. "hello.txt" or "etc/passwd").
     *
     * @param path  Null-terminated path relative to the ramdisk root
     * @return Pointer to the found Inode, or nullptr if not found
     */
    Inode* lookup(const char* path) override;

    /**
     * @brief Get the base address of the ramdisk archive
     * @return Pointer to the start of the archive, or nullptr if not mounted
     */
    const void* base() const;

    /**
     * @brief Get the total size of the ramdisk archive in bytes
     * @return Size in bytes, or 0 if not mounted
     */
    uint64_t total_size() const;

    /**
     * @brief Get the number of file entries found during mount
     * @return Number of entries
     */
    uint32_t entry_count() const;

private:
    /// Ops instances for file and directory inodes
    InodeOps* file_ops_;
    InodeOps* dir_ops_;

    /// Pointer to the start of the embedded archive
    const uint8_t* base_{};

    /// Total size of the archive in bytes
    uint64_t size_{};

    /// Number of valid file entries found during mount
    uint32_t entry_count_{};

    /// Pre-allocated entry table (each entry includes its own Inode)
    RamdiskEntry entries_[RAMDISK_MAX_ENTRIES];

    /// Root directory inode (for readdir support)
    Inode root_inode_{};

    /// Context for root directory readdir
    RamdiskDirContext root_ctx_{};
};

}  // namespace cinux::fs
