#!/usr/bin/env python3
"""generate_kallsyms.py — emit a C++ KALLSYMS table from a linked kernel ELF.

Reads `nm -n <elf>`, keeps the text-section function symbols (T/t), and writes a
C++ source defining the {address, name} table that kallsyms_set_table() consumes
at boot. The table is ascending by address (nm -n guarantees this), matching the
contract of kernel/lib/kallsyms.hpp.

Why this is safe to regenerate post-build (F-INFRA I-5, R4):
  linker.ld places .rodata INSIDE the .text output section, AFTER *(.text .*).
  The kallsyms table is const data -> .rodata, so it links AFTER every function.
  Adding the table therefore does not move any .text function address it records:
  a single nm pass over the table-less (or prior) ELF yields addresses that stay
  valid once the real table is compiled in. The build converges in two passes.

Usage:
    python3 scripts/generate_kallsyms.py <elf> <output.cpp>
"""

import os
import subprocess
import sys
import tempfile

HEADER = """\
// AUTO-GENERATED by scripts/generate_kallsyms.py from nm of the linked ELF.
// DO NOT EDIT -- regenerated as a POST_BUILD step (F-INFRA I-5).

#include <stddef.h>
#include <stdint.h>

#include "kernel/lib/kallsyms.hpp"

// Text-section function symbols, ascending by address. .rodata (where this
// table lands) is placed after .text by linker.ld, so these addresses are
// stable regardless of this table's presence/size.
extern "C" const cinux::lib::KallsymEntry g_kallsyms_table[] = {
"""

FOOTER = """\
};

extern "C" const size_t g_kallsyms_count = sizeof(g_kallsyms_table) / sizeof(g_kallsyms_table[0]);
"""


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_kallsyms.py <elf> <output.cpp>", file=sys.stderr)
        return 2

    elf_path, out_path = sys.argv[1], sys.argv[2]
    nm = subprocess.run(["nm", "-n", "--defined-only", elf_path],
                        capture_output=True, text=True, check=True)

    entries = []
    for line in nm.stdout.splitlines():
        parts = line.split()
        # nm -n line shape: "<hexaddr> T <name>" (or t/w for weak). Keep T/t only
        # (text symbols = functions). Drop section markers ('$' names) and local
        # GCC-generated labels that start with '.' or end in '.cfi'/'.isra' etc.
        if len(parts) < 3:
            continue
        addr_s, sym_type, name = parts[0], parts[1], parts[2]
        if sym_type not in ("T", "t"):
            continue
        # Skip compiler-generated pseudo-labels (not useful in a backtrace).
        if name.startswith(".") or name.startswith("_"):
            # keep underscored C symbols (e.g. _start, __kernel_stack_top are
            # meaningful); only drop dotted GCC labels like .L1, .text.startup
            if name.startswith("."):
                continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        entries.append((addr, name))

    if not entries:
        content = HEADER + "};\n\n" + 'extern "C" const size_t g_kallsyms_count = 0;\n'
        print(f"kallsyms: no text symbols in {elf_path} (empty table)", file=sys.stderr)
    else:
        body = "".join(
            f'    {{0x{a:016x}ULL, "{n.replace(chr(92), chr(92)*2).replace(chr(34), chr(92) + chr(34))}"}},\n'
            for a, n in entries
        )
        content = HEADER + body + FOOTER
        print(f"kallsyms: {len(entries)} symbols -> {out_path}", file=sys.stderr)

    # Write only if content changed (preserve mtime). The POST_BUILD step runs on
    # every build; an unconditional rewrite would bump mtime and force a recompile
    # -> relink -> regenerate loop every time. Once addresses converge (they do:
    # .rodata is after .text in linker.ld, so the table never moves functions),
    # the content is stable and no further rebuild is triggered.
    try:
        with open(out_path) as fh:
            if fh.read() == content:
                return 0  # unchanged -- keep mtime, break the rebuild loop
    except OSError:
        pass

    out_dir = os.path.dirname(os.path.abspath(out_path)) or "."
    fd, tmp = tempfile.mkstemp(dir=out_dir, suffix=".cpp.tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        os.replace(tmp, out_path)
    except OSError:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return 0


if __name__ == "__main__":
    sys.exit(main())
