/**
 * @file kernel/mini/test/test_stress_big_kernel.cpp
 * @brief Stress test: load a large (up to 1GB) synthetic ELF and verify data
 *
 * Uses the two-phase loader API to load a synthetic ELF generated by
 * generate_large_elf.py. Verifies:
 *   - ELF magic after Phase 1
 *   - Data pattern integrity at sampled offsets
 *   - Entry point correctness
 */

#include "../arch/x86_64/paging.hpp"
#include "../big_kernel_loader.hpp"
#include "../driver/ata.hpp"
#include "../elf_loader.hpp"
#include "../lib/crc32.h"
#include "../lib/kprintf.h"
#include "kernel_test.h"

using cinux::mini::loader::BIG_KERNEL_LOAD_ADDR;
using cinux::mini::loader::BIG_KERNEL_ENTRY_VADDR;
using cinux::mini::loader::BIG_KERNEL_LBA;
using cinux::mini::loader::BigKernelLoadState;
using cinux::mini::loader::load_big_kernel_phase1;
using cinux::mini::loader::load_big_kernel_phase2;
using cinux::mini::lib::kprintf;

// The stress test ELF is placed at a different LBA from the normal big kernel.
// Must match the CMake stress test image configuration.
// Use LBA 2048 (1MB into the disk) to avoid collision with the normal big kernel.
constexpr uint64_t STRESS_KERNEL_LBA = 2048;

// ============================================================
// Test 1: Phase 1 headers parsed correctly
// ============================================================

namespace test_stress_phase1 {

void test_phase1_headers() {
    BigKernelLoadState state;
    bool               ok = load_big_kernel_phase1(STRESS_KERNEL_LBA, state);
    TEST_ASSERT_TRUE(ok);

    const auto* magic = reinterpret_cast<const uint8_t*>(BIG_KERNEL_LOAD_ADDR);
    TEST_ASSERT_EQ(magic[0], 0x7F);
    TEST_ASSERT_EQ(magic[1], 'E');
    TEST_ASSERT_EQ(magic[2], 'L');
    TEST_ASSERT_EQ(magic[3], 'F');

    kprintf("  Stress ELF: %u bytes (%u sectors)\n", static_cast<uint32_t>(state.total_elf_size),
            state.total_sectors);
    TEST_ASSERT(state.total_elf_size > 1024 * 1024);  // At least 1MB
}
}  // namespace test_stress_phase1

// ============================================================
// Test 2: Phase 2 loads and data pattern verifies
// ============================================================

namespace test_stress_phase2 {

/// Verify the data pattern at sampled offsets.
/// Pattern: byte at offset = (offset >> 12) & 0xFF
/// Special case: offset 0 is 0xFA ('cli') instead of the pattern.
bool verify_pattern(uint64_t base, uint64_t size) {
    // Sample every 1MB (1024 samples for 1GB)
    uint64_t step          = 1024 * 1024;
    uint32_t checked       = 0;
    uint32_t total_samples = static_cast<uint32_t>(size / step);
    for (uint64_t off = 0; off < size; off += step) {
        uint8_t actual   = *reinterpret_cast<volatile uint8_t*>(base + off);
        uint8_t expected = (off == 0) ? 0xFA : static_cast<uint8_t>((off >> 12) & 0xFF);
        if (actual != expected) {
            kprintf("  MISMATCH at offset 0x%p: expected 0x%02x got 0x%02x\n",
                    reinterpret_cast<const void*>(off), expected, actual);
            return false;
        }
        checked++;
        // Log every 128 MB
        if (checked % 128 == 0) {
            kprintf("  Verify progress: %u / %u samples (%u%%)\n", checked, total_samples,
                    checked * 100 / total_samples);
        }
    }
    kprintf("  Pattern verified at %u sample points\n", checked);
    return true;
}

void test_phase2_load_and_verify() {
    // Re-run Phase 1 (state from test 1 is not shared across RUN_TEST)
    BigKernelLoadState state;
    bool               ok = load_big_kernel_phase1(STRESS_KERNEL_LBA, state);
    TEST_ASSERT_TRUE(ok);

    uint64_t entry = load_big_kernel_phase2(state, STRESS_KERNEL_LBA);
    TEST_ASSERT(entry != 0);
    kprintf("  Entry point: 0x%p\n", reinterpret_cast<void*>(entry));
    TEST_ASSERT_EQ(entry, BIG_KERNEL_ENTRY_VADDR);

    // The synthetic ELF has one PT_LOAD at p_paddr=0x1000000
    // with memsz = filesz. Verify the data pattern.
    TEST_ASSERT(state.phnum >= 1);
    uint64_t seg_base = state.phdrs[0].p_paddr;
    uint64_t seg_size = state.phdrs[0].p_memsz;

    kprintf("  Verifying data pattern (%u MB)...\n",
            static_cast<uint32_t>(seg_size / (1024 * 1024)));

    TEST_ASSERT_TRUE(verify_pattern(seg_base, seg_size));
}
}  // namespace test_stress_phase2

// ============================================================
// Test Entry Point
// ============================================================

extern "C" void run_stress_big_kernel_tests() {
    TEST_SECTION("Stress Test: Large Kernel Load");

    RUN_TEST(test_stress_phase1::test_phase1_headers);
    RUN_TEST(test_stress_phase2::test_phase2_load_and_verify);

    TEST_SUMMARY();
}
